name: checkUnwantedFiles

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  UNWANTED_NAME_PATTERNS: "*.pdb *.ilk *user *.ncb *.suo *.log *.dmp *.zip imgui.ini desktop.ini dxcompiler.dll dxil.dll"

  UNWANTED_DIR_PATTERNS: "generated x64 win32 arm64 .vs bin ipch logs Dump"

jobs:
  check_files:
    name: 不要なファイルを検索
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: 不要なファイルとディレクトリを検索 (bash)
        run: |
          # ディレクトリ条件を構築 (最初の不要な -o を後で削除)
          DIR_CONDITIONS=()
          for pattern in $UNWANTED_DIR_PATTERNS; do
            DIR_CONDITIONS+=( -o -iname "$pattern")
          done
          unset DIR_CONDITIONS[0]

          # ファイル条件を構築 (最初の不要な -o を後で削除)
          NAME_CONDITIONS=()
          for pattern in $UNWANTED_NAME_PATTERNS; do
            NAME_CONDITIONS+=(-o -iname "$pattern")
          done
          unset NAME_CONDITIONS[0]

          # 1回の find 実行で全件を検索
          # 1. .git を除外
          # 2. 不要なディレクトリを検索(-typr d)し、見つけたらパスを出力(-print)し、その中身を枝刈り(-prune)
          # 3. または (-o) 不要なファイル検索(-type f)し、パスを出力(-print)
          UNWANTED_LIST=$(find . -path "./.git" -prune -o \
            \( \( "${DIR_CONDITIONS[@]}"\) -a -type d -print -prune \) -o \
            \( \( "${NAME_CONDITIONS[@]}"\) -a -type f -print \) \
          )

          # 検出結果があればエラーとして出力し、失敗させる
          if [ -n "$UNWANTED_LIST" ]; then
            echo "::error::不要なファイルまたはディレクトリが見つかりました！"
            echo "$UNWANTED_LIST"
            exit 1
          fi

          echo "リポジトリはクローンです"